sudo: required
jobs:
  include:
  - stage: Build
    os: linux
    language: cpp 
    script:
    - mkdir build_linux
    - cd build_linux
    - cmake -DCMAKE_BUILD_TYPE=Release -DWITH_TESTS=0 -DWITH_GFLAGS=0 -DWITH_BENCHMARK_TOOLS=0 -DWITH_TOOLS=0 -DWITH_CORE_TOOLS=1 ..
    - make
    workspaces:
      create:
        name: bin_linux
        paths:
        - build_linux
  - stage: Build
    os: osx
    language: cpp
    script:
    - mkdir build_osx
    - cd build_osx
    - cmake -DCMAKE_BUILD_TYPE=Release -DWITH_TESTS=0 -DWITH_GFLAGS=0 -DWITH_BENCHMARK_TOOLS=0 -DWITH_TOOLS=0 -DWITH_CORE_TOOLS=1 ..
    - make
    workspaces:
      create:
        name: bin_osx
        paths:
        - build_osx
  - stage: Build
    os: windows
    language: cpp
    script:
    - mkdir build_win
    - cd build_win
    - cmake -DCMAKE_BUILD_TYPE=Release -DWITH_TESTS=0 -DWITH_GFLAGS=0 -DWITH_BENCHMARK_TOOLS=0 -DWITH_TOOLS=0 -DWITH_CORE_TOOLS=1 ..
    - make
    workspaces:
      create:
        name: bin_win
        paths:
        - build_win
  - stage: Nuget_build
    language: csharp
    dotnet: 5.0
    mono: none
    dist: focal
    addons:
      apt:
        packages:
        - dotnet-sdk-3.1
        - nuget
    workspaces:
      use:
      - bin_linux
      - bin_osx
      - bin_win
    env:
      global:
      - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
    install:
    - mkdir lib
    - mkdir lib/linux-x64
    - mkdir lib/win-x54
    - mkdir lib/osx-x64
    - cp build_linux/librocksdb.so lib/linux-x64/librocksdb.so
    - cp build_osx/librocksdb.dylib lib/osx-x64/librocksdb.dylib
    - cp build_win/rocksdb.dll lib/win-x64/rocksdb.dll
    script:
    - nuget pack
    - dotnet nuget push RocksDb.Native.*.nupkg -k $NUGETKEY -s https://api.nuget.org/v3/index.json --timeout 600 --skip-duplicate
    deploy:
      provider: releases
      api_key: "$GITHUB_TOKEN1"
      file_glob: true
      file:
      - ../RocksDb.Native.*nupkg
      skip_cleanup: true
      draft: true
      on:
        tags: true
